// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5YBmw5AlwL0K1bScCLc5qihACVfBpxs',
    appId: '1:663170647064:web:3f850062b615ce3c4e6f6d',
    messagingSenderId: '663170647064',
    projectId: 'urban-lens-2429e',
    authDomain: 'urban-lens-2429e.firebaseapp.com',
    storageBucket: 'urban-lens-2429e.firebasestorage.app',
    measurementId: 'G-4F9HZRT2W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Byl-cyoUSe-RkR0hX3wUBN0mV_-ZPCE',
    appId: '1:663170647064:android:9852f244a7601bd14e6f6d',
    messagingSenderId: '663170647064',
    projectId: 'urban-lens-2429e',
    storageBucket: 'urban-lens-2429e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjLtgiKmw38Ko1vmO8MOO2qoVA0ff6auI',
    appId: '1:663170647064:ios:223c7e0acb3848c84e6f6d',
    messagingSenderId: '663170647064',
    projectId: 'urban-lens-2429e',
    storageBucket: 'urban-lens-2429e.firebasestorage.app',
    iosBundleId: 'com.example.urbanLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjLtgiKmw38Ko1vmO8MOO2qoVA0ff6auI',
    appId: '1:663170647064:ios:223c7e0acb3848c84e6f6d',
    messagingSenderId: '663170647064',
    projectId: 'urban-lens-2429e',
    storageBucket: 'urban-lens-2429e.firebasestorage.app',
    iosBundleId: 'com.example.urbanLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5YBmw5AlwL0K1bScCLc5qihACVfBpxs',
    appId: '1:663170647064:web:23e5a74e6534972b4e6f6d',
    messagingSenderId: '663170647064',
    projectId: 'urban-lens-2429e',
    authDomain: 'urban-lens-2429e.firebaseapp.com',
    storageBucket: 'urban-lens-2429e.firebasestorage.app',
    measurementId: 'G-K5573PCRZS',
  );
}
